spring.application.name=careerflow
spring.security.user.name=admin
spring.security.user.password=admin123


# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/careerflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
