package com.careerflow.timeline;

public enum TimelineEventType {
    OPPORTUNITY_SAVED,
    OPPORTUNITY_UPDATED,
    OPPORTUNITY_CONVERTED,
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    OA_SCHEDULED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    REFERRAL_REQUESTED,
    REFERRAL_STATUS_CHANGED,
    FOLLOW_UP_SENT,
    OFFER_RECEIVED,
    ACTION_COMPLETED,
    NOTE
}
