package com.careerflow.audit;

public enum AuditAction {
    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_DELETED,
    COMPANY_CREATED,
    COMPANY_UPDATED,
    COMPANY_DELETED,
    INTERVIEW_CREATED,
    INTERVIEW_UPDATED,
    INTERVIEW_DELETED,
    REFERRAL_CREATED,
    REFERRAL_UPDATED,
    REFERRAL_DELETED,
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_ROLE_CHANGED,
    WORKSPACE_UPDATED,
    WORKSPACE_DELETED
}
